export const bankNameToIdMap: { [key: string]: string } = {
  "Vietcombank": "VCB",
  "MBBank": "MB",
  "ACB": "ACB",
  "Techcombank": "TCB",
  "BIDV": "BIDV",
  "Agribank": "AGR",
  "VPBank": "VPB",
  "Sacombank": "STB",
  "TPBank": "TPB",
  "VietinBank": "CTG",
  "Eximbank": "EIB",
  "DongA Bank": "DAB",
  "HDBank": "HDB",
  "Maritime Bank": "MSB",
  "OCB": "OCB",
  "SHB": "SHB",
  "SCB": "SCB",
  "SeABank": "SEAB",
  "VIB": "VIB",
  "PVcomBank": "PVC",
  "Bac A Bank": "BAB",
  "GPBank": "GPB",
  "Kienlongbank": "KLB",
  "LienVietPostBank": "LPB",
  "Nam A Bank": "NAB",
  "NCB": "NCB",
  "OceanBank": "OCB", // OCB is also for Orient Commercial Bank
  "Public Bank Vietnam": "PBVN",
  "Saigonbank": "SGB",
  "Standard Chartered": "SCVN",
  "Shinhan Bank": "SHBVN",
  "UOB Vietnam": "UOB",
  "Woori Bank": "WVN",
  "Hong Leong Bank": "HLBVN",
  "Indovina Bank": "IVB",
  "CIMB Bank": "CIMB",
  "HSBC Vietnam": "HSBC",
  "CitiBank Vietnam": "CITI",
  "ANZ Vietnam": "ANZ",
  "Bank of China": "BOC",
  "Bank of Communications": "BOCOM",
  "DBS Bank": "DBS",
  "Far East National Bank": "FENB",
  "First Commercial Bank": "FCB",
  "Mega International Commercial Bank": "MICB",
  "E.SUN Commercial Bank": "ESUN",
  "Cathay United Bank": "CUB",
  "Taipei Fubon Commercial Bank": "TFBC",
  "Industrial Bank of Korea": "IBK",
  "KEB Hana Bank": "KEBHN",
  "Sumitomo Mitsui Banking Corporation": "SMBC",
  "Mizuho Bank": "MIZUHO",
  "Bank of Tokyo-Mitsubishi UFJ": "BTMU",
  "JP Morgan Chase Bank": "JPM",
  "BNP Paribas": "BNPP",
  "Deutsche Bank": "DB",
  "Standard Bank": "SBSA",
  "Commonwealth Bank of Australia": "CBA",
  "Bank of America": "BOFA",
  "Wells Fargo Bank": "WF",
  "Bank of New York Mellon": "BNYM",
  "Credit Suisse": "CS",
  "UBS AG": "UBS",
  "Rabobank": "RABO",
  "ING Bank": "ING",
  "Societe Generale": "SOGE",
  "Commerzbank": "CBK",
  "Dresdner Bank": "DRBNK",
  "Westpac Banking Corporation": "WBC",
  "National Australia Bank": "NABAU",
  "Bank of Queensland": "BOQ",
  "Suncorp Bank": "SUN",
  "Bendigo and Adelaide Bank": "BEN",
  "Macquarie Bank": "MQB",
  "Bank of Western Australia": "BWA",
  "Bank of South Australia": "BSA",
  "Bank of Melbourne": "BOM",
  "St.George Bank": "SGB",
  "Bank of China (Hong Kong)": "BOCHK",
  "China Construction Bank": "CCB",
  "Industrial and Commercial Bank of China": "ICBC",
  "Agricultural Bank of China": "ABC",
  "China Merchants Bank": "CMB",
  "China Everbright Bank": "CEB",
  "Ping An Bank": "PAB",
  "Shanghai Pudong Development Bank": "SPDB",
  "China CITIC Bank": "CITIC",
  "China Minsheng Bank": "CMBC",
  "Huaxia Bank": "HXB",
  "Guangdong Development Bank": "GDB",
  "Industrial Bank": "IB",
  "Zhejiang Chouzhou Commercial Bank": "ZCCB",
  "Bank of Beijing": "BOB",
  "Bank of Shanghai": "BOS",
  "Bank of Jiangsu": "BOJ",
  "Bank of Ningbo": "BON",
  "Bank of Hangzhou": "BOH",
  "Bank of Chengdu": "BOCD",
  "Bank of Chongqing": "BOCQ",
  "Bank of Dalian": "BOD",
  "Bank of Fuzhou": "BOF",
  "Bank of Guangzhou": "BOG",
  "Bank of Harbin": "BOHB",
  "Bank of Hefei": "BOHF",
  "Bank of Hohhot": "BOHH",
  "Bank of Jinzhou": "BOJZ",
  "Bank of Kunming": "BOKM",
  "Bank of Lanzhou": "BOLZ",
  "Bank of Liuzhou": "BOLZ",
  "Bank of Luoyang": "BOLO",
  "Bank of Nanchang": "BONC",
  "Bank of Nanjing": "BONJ",
  "Bank of Nanning": "BONN",
  "Bank of Qingdao": "BOQD",
  "Bank of Rizhao": "BORZ",
  "Bank of Shaoxing": "BOSX",
  "Bank of Shenyang": "BOSY",
  "Bank of Suzhou": "BOSZ",
  "Bank of Taizhou": "BOTZ",
  "Bank of Tianjin": "BOTJ",
  "Bank of Wenzhou": "BOWZ",
  "Bank of Wuxi": "BOWX",
  "Bank of Xi'an": "BOXA",
  "Bank of Xiamen": "BOXM",
  "Bank of Xining": "BOXN",
  "Bank of Yangzhou": "BOYZ",
  "Bank of Yantai": "BOYT",
  "Bank of Zhengzhou": "BOZZ",
  "Bank of Zhongshan": "BOZS",
  "Bank of Zhuhai": "BOZH",
  "Changsha Bank": "CSB",
  "Chengdu Rural Commercial Bank": "CRCB",
  "Chongqing Rural Commercial Bank": "CQRCB",
  "Dalian Bank": "DLB",
  "Fujian Haixia Bank": "FHB",
  "Guangzhou Rural Commercial Bank": "GZRCB",
  "Harbin Bank": "HRBB",
  "Hefei Bank": "HFB",
  "Hohhot Bank": "HHB",
  "Huishang Bank": "HSB",
  "Jiangsu Bank": "JSB",
  "Jinzhou Bank": "JZB",
  "Kunming Bank": "KMB",
  "Lanzhou Bank": "LZB",
  "Liuzhou Bank": "LHB",
  "Luoyang Bank": "LYB",
  "Nanchang Bank": "NCB",
  "Nanjing Bank": "NJB",
  "Nanning Bank": "NNB",
  "Qingdao Bank": "QDB",
  "Rizhao Bank": "RZB",
  "Shaoxing Bank": "SXB",
  "Shenyang Rural Commercial Bank": "SYRCB",
  "Suzhou Bank": "SZB",
  "Taizhou Bank": "TZB",
  "Tianjin Rural Commercial Bank": "TJRCB",
  "Wenzhou Bank": "WZB",
  "Wuxi Bank": "WXB",
  "Xi'an Bank": "XAB",
  "Xiamen Bank": "XMB",
  "Xining Bank": "XNB",
  "Yangzhou Bank": "YZB",
  "Yantai Bank": "YTB",
  "Zhengzhou Bank": "ZZB",
  "Zhongshan Rural Commercial Bank": "ZSRCB",
  "Zhuhai Rural Commercial Bank": "ZHRCB",
};

export const getBankIdFromName = (bankName: string): string | undefined => {
  if (!bankName) return undefined;
  const normalizedName = bankName.toLowerCase().replace(/\s/g, '');
  for (const key in bankNameToIdMap) {
    const normalizedKey = key.toLowerCase().replace(/\s/g, '');
    if (normalizedKey.includes(normalizedName) || normalizedName.includes(normalizedKey)) {
      return bankNameToIdMap[key];
    }
  }
  return undefined;
};